[mypy]
python_version = 3.12
strict = True
warn_unused_configs = True
warn_return_any = True
warn_unused_ignores = True
no_implicit_optional = True
disallow_any_generics = True
show_error_codes = True
pretty = True

[mypy-core_lib._core]
ignore_missing_imports = True
